# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
