# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florist_app', '0003_auto_20160411_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='description',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
