# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('florist_app', '0004_arrangement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='florist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='florist_app.Florist'),
        ),
    ]
