# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florist_app', '0005_auto_20160413_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
