# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('florist_app', '0006_auto_20160413_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='arrangement',
        ),
        migrations.AddField(
            model_name='basket',
            name='arrangement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='florist_app.Arrangement'),
            preserve_default=False,
        ),
    ]
