# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('florist_app', '0007_auto_20160413_2047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='Cart',
        ),
    ]
