# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 00:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('florist_app', '0009_cart_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
