# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('florist_app', '0011_auto_20160419_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Enjoyer',
        ),
    ]
