# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florist_app', '0013_auto_20160419_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
