# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import florist.custom_storages


class Migration(migrations.Migration):

    dependencies = [
        ('florist_app', '0014_cart_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=florist.custom_storages.MediaStorage(), upload_to='uploads'),
        ),
    ]
